
# ---------------------------------------------------------------------------

.bootstrap_and_functions: &bootstrap_and_functions |
  # bootstrap environment variables and declare step functions

  [[ "$TRACE" ]] && set -x

  # output the current environment for debugging purposes
  function runner_env() {
    echo ""; echo ""
    echo "---------------------------------------------------------------------------"
    echo "ENVIRONMENT"
    echo "---------------------------------------------------------------------------"
    env
    echo "---------------------------------------------------------------------------"
    echo "FILES"
    echo "---------------------------------------------------------------------------"
    ls -latr
    echo "---------------------------------------------------------------------------"
    echo ""; echo ""
  }

  # this can set in the runner as the --pre-build-script flag
  function bootstrap_all() {
    [[ "$DEBUG" ]] && runner_env
    apk add --no-cache --update make
    apk add --update openssl curl tar gzip bash ca-certificates git
    git clone https://github.com/piersharding/submake.git --branch master --single-branch --depth 1 ./citools
  }


check-code-standards-flake8:
  stage: check
  image: docker:stable
  before_script:
    - *bootstrap_and_functions
    - bootstrap_all
    - 'apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev'
    - 'apk add --no-cache --update python3'
    - 'pip3 install flake8'

  script:
    - 'make check_flake8'
  tags:
    - docker
